from pydantic import BaseModel, Field
from typing import Literal, Optional

class UploadUrlResponse(BaseModel):
    upload_url: str = Field(
        ...,
        description="Temporary pre-signed URL to upload the image."
    )
    image_key: str = Field(
        ...,
        description="Unique file identifier generated by the server.",
    )

class MorphologicalParams(BaseModel):
    operation: Literal["dilate", "erode", "opening", "closing", "contour", "top_hat", "bottom_hat"] = Field(
        ..., description="Type of morphological operation to apply to the image."
    )
    shape: Literal["rect", "ellipse", "cross"] = Field(
        ..., description="Shape of the structuring element."
    )
    sizeX: int = Field(
        ..., gt=0, le=19,
        description="Width of the structuring element."
    )
    sizeY: int = Field(
        ..., gt=0, le=19,
        description="Height of the structuring element."
    )

class JobCreateRequest(BaseModel):
    image_key: str = Field(
        ...,
        description="The image key previously obtained from the /upload_url endpoint."
    )
    params: MorphologicalParams

class JobCreateResponse(BaseModel):
    job_id: str = Field(
        ...,
        description="Unique UUID of the asynchronous job created."
    )

class JobStatusResponse(BaseModel):
    status: str = Field(
        ...,
        description="Current state of the processing job.",
    )
    result_url: Optional[str] = Field(
        None,
        description="Temporary pre-signed download URL for the processed image. Only present if status is 'done'.",
    )
    message: Optional[str] = Field(
        None,
        description="Error message detailing the processing failure. Only present if status is 'failed'.",
    )

    @classmethod
    def from_job(cls, job: dict):
        return cls(
            status=job["status"],
            result_url=job.get("result_url") if job["status"] == "done" else None,
            message=job.get("error") if job["status"] == "error" else None
        )